# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI_d.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(498, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.txtURL = QtWidgets.QLineEdit(self.centralwidget)
        self.txtURL.setGeometry(QtCore.QRect(110, 70, 331, 31))
        self.txtURL.setObjectName("txtURL")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.txtPackage = QtWidgets.QTextEdit(self.centralwidget)
        self.txtPackage.setGeometry(QtCore.QRect(110, 130, 331, 211))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtPackage.setFont(font)
        self.txtPackage.setObjectName("txtPackage")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 350, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 400, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.txtFocus = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFocus.setGeometry(QtCore.QRect(110, 360, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtFocus.setFont(font)
        self.txtFocus.setAlignment(QtCore.Qt.AlignCenter)
        self.txtFocus.setObjectName("txtFocus")
        self.txtZoom = QtWidgets.QLineEdit(self.centralwidget)
        self.txtZoom.setGeometry(QtCore.QRect(110, 410, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtZoom.setFont(font)
        self.txtZoom.setAlignment(QtCore.Qt.AlignCenter)
        self.txtZoom.setObjectName("txtZoom")
        self.btnSetFocus = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetFocus.setGeometry(QtCore.QRect(190, 360, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSetFocus.setFont(font)
        self.btnSetFocus.setObjectName("btnSetFocus")
        self.btnSetZoom = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetZoom.setGeometry(QtCore.QRect(190, 410, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSetZoom.setFont(font)
        self.btnSetZoom.setObjectName("btnSetZoom")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 360, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.btnSetAutoFocus = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetAutoFocus.setGeometry(QtCore.QRect(340, 400, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSetAutoFocus.setFont(font)
        self.btnSetAutoFocus.setObjectName("btnSetAutoFocus")
        self.btnRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefresh.setGeometry(QtCore.QRect(20, 260, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnRefresh.setFont(font)
        self.btnRefresh.setObjectName("btnRefresh")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 470, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.btnCompile = QtWidgets.QPushButton(self.centralwidget)
        self.btnCompile.setGeometry(QtCore.QRect(260, 490, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnCompile.setFont(font)
        self.btnCompile.setObjectName("btnCompile")
        self.lblFocusmm = QtWidgets.QLabel(self.centralwidget)
        self.lblFocusmm.setGeometry(QtCore.QRect(130, 470, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lblFocusmm.setFont(font)
        self.lblFocusmm.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFocusmm.setObjectName("lblFocusmm")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 510, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lblZoom = QtWidgets.QLabel(self.centralwidget)
        self.lblZoom.setGeometry(QtCore.QRect(130, 510, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lblZoom.setFont(font)
        self.lblZoom.setAlignment(QtCore.Qt.AlignCenter)
        self.lblZoom.setObjectName("lblZoom")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "IB9391-IHT"))
        self.label_2.setText(_translate("MainWindow", "URL:"))
        self.txtURL.setText(_translate("MainWindow", "http://192.168.50.40/cgi-bin/admin/remotefocus.cgi"))
        self.label_3.setText(_translate("MainWindow", "Package:"))
        self.label_4.setText(_translate("MainWindow", "Focus:"))
        self.label_5.setText(_translate("MainWindow", "Zoom:"))
        self.txtFocus.setText(_translate("MainWindow", "822"))
        self.txtZoom.setText(_translate("MainWindow", "64"))
        self.btnSetFocus.setText(_translate("MainWindow", "Setting"))
        self.btnSetZoom.setText(_translate("MainWindow", "Setting"))
        self.label_6.setText(_translate("MainWindow", "AutoFocus"))
        self.btnSetAutoFocus.setText(_translate("MainWindow", "Setting"))
        self.btnRefresh.setText(_translate("MainWindow", "Refresh"))
        self.label_7.setText(_translate("MainWindow", "Focus(mm):"))
        self.btnCompile.setText(_translate("MainWindow", "換算"))
        self.lblFocusmm.setText(_translate("MainWindow", "Unknow"))
        self.label_9.setText(_translate("MainWindow", "Zoom:"))
        self.lblZoom.setText(_translate("MainWindow", "Unknow"))

